config/routes.rb
Rails.application.routes.draw do

  resources :welcome
  resources :sites

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articleurl_controller.rb
class ArticleurlController < ApplicationController
# URLにアクセスするためのライブラリの読み込み
require 'open-uri'
# Nokogiriライブラリの読み込み
require 'nokogiri'

	def article_model
		@tetugaku = Nokogiri::HTML.parse(url_set("http://blog.livedoor.jp/nwknews/"), nil, 'utf-8')

		@tetugaku.css('div.article-header').each do |doc|
			article_link(@tetugaku.title, 'div.article-title-outer > h2 > a', 'div.article-date-outer > abbr.updated', doc)
		end
	end

	def article_link(hpname, article, date, doc)
		@article = Article.new
		@article.hpname = hpname
		@article.title = doc.css(article).text
		@article.url = doc.css(article)[0][:href]
		@article.date = DateTime.parse(doc.css(date)[0][:title])

		@article.save
	end

	def url_set(url)
		charset = nil
		html = open(url) do |f|
			charset = f.charset # 文字種別を取得
			f.read # htmlを読み込んで変数htmlに渡す
		end
		return html
	end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
	before_action :set_site, only: [:show, :edit, :update, :destroy]

	def index
		@sites = Site.all
	end

 	def new
		@site = Site.new
	end

	def edit		
	end

	def show		
	end

	def create
		@site = Site.new(site_params)
		if @site.save
			redirect_to site_path(@site)
		else
			render 'new'
		end
	end

	def update
		if @site.update(site_params)
			redirect_to site_path(@site)
		else
			render 'new'
		end
	end

	def destroy	
		@site.destroy

		redirect_to sites_path	
	end

	def site_params
		params.require(:site).permit(:sitename, :order)
	end

	def set_site
		@site = Site.find params[:id]
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
# URLにアクセスするためのライブラリの読み込み
require 'open-uri'
# Nokogiriライブラリの読み込み
require 'nokogiri'
	def index
		@articles = Article.all.order(articledate: :desc)
		@sites = Site.all

		# htmlをパース(解析)してオブジェクトを生成
		#@tetugaku = Nokogiri::HTML.parse(url_set("http://blog.livedoor.jp/nwknews/"), nil, 'utf-8')
		#itsoku = Nokogiri::HTML.parse(url_set("http://blog.livedoor.jp/itsoku/"), nil, 'utf-8')
		#@burusoku = Nokogiri::HTML.parse(url_set("http://burusoku-vip.com/"), nil, 'utf-8')
		#@viper = Nokogiri::HTML.parse(url_set("http://blog.livedoor.jp/news23vip/"), nil, 'utf-8')
		#@inazuma = Nokogiri::HTML.parse(url_set("http://inazumanews2.com/"), nil, 'utf-8')
=begin

		@gara = Nokogiri::HTML.parse(url_set("http://karapaia.livedoor.biz/"), nil, 'utf-8')
		@ajajasita = Nokogiri::HTML.parse(url_set("http://blog.livedoor.jp/chihhylove/"), nil, 'utf-8')
=end
	end

	def show
		p '---------------------------------------------'
		p params[:sitename]
		@articles = Article.where('hpname like ?', "%" + params[:sitename] + "%").order(articledate: :desc)
		@sites = Site.all

		render 'index'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
  <title>まとめのまとめ</title>
  <meta name="description" content="主要まとめサイトのトップ記事をまとめる">
  <meta name="keywords" content="まとめサイト,まとめ,2ch,まとめのまとめ">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrapper">
		<div id="header">
			<strong>まとめをまとめる</strong>
		</div>
		<div id="content">
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/sites/edit.html.erb
<%= form_for @site do |f| %>
	<% if @site.errors.any? %>
		<%= @site.errors.count %>個のエラーがあります。<br>
		<%= @site.errors.full_messages.each do |msg| %>
			<%= msg %><br>
		<% end -%>
	<% end -%>

	<%= f.text_field :sitename %><br>
	<%= f.text_field :order %><br>
	<%= f.submit %>
<% end -%>

app/views/sites/index.html.erb
<h1>Sites#index</h1>
<%= link_to "新規記事作成", new_site_path %>
<hr>
<% @sites.each do |site| %>
	<%= site.sitename %>
	<%= link_to "編集", edit_site_path(site) %>
	<%= site.order %>
	<hr>
<% end %>

app/views/sites/new.html.erb
<%= form_for @site do |f| %>
	<% if @site.errors.any? %>
		<%= @site.errors.count %>個のエラーがあります。<br>
		<%= @site.errors.full_messages.each do |msg| %>
			<%= msg %><br>
		<% end -%>
	<% end -%>

	<%= f.text_field :sitename %><br>
	<%= f.text_field :order %><br>
	<%= f.submit %>
<% end -%>

app/views/sites/show.html.erb
<h1><%= @site.sitename %></h1>
<p><%= @site.order %></p>
<%= link_to "記事一覧に戻る", sites_path %>

app/views/welcome/_article_link.html.erb
<%#= link_to doc.text, doc["href"], :target=>["_blank"], class: :article_link %>
<%#= 取得してきた日付と時間のstirngテキストを日付型に変換 %>
<% @datetime = DateTime.parse(doc.css(date)[0][:title]) %>
<%#= 日付の書式をフォーマット %>
<%= @datetime.strftime('%m月%d日 %H:%M') %><br>
<%= link_to doc.css(article).text, doc.css(article)[0][:href], :target=>["_blank"], class: :article_link %><br><br>

app/views/welcome/index.html.erb
<div id="articles">
<% @articles.each do |article| %>
	<p class="titledate"><%= article.hpname %> : <%= article.articledate.strftime('%m月%d日 %H:%M') %></p>
	<%= link_to article.title, article.url, :target=>["_blank"], class: :article_link %><hr>
<% end -%>
</div>

<div id="side_bar">
	<%= link_to "全部表示", welcome_index_path %><br><br>
	<% @sites.each do |site| %>
		<%= link_to site.sitename, welcome_path(site, sitename: site.sitename) %><br><br>
	<% end -%>
</div>
<div id="footer"></div>